# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13cfaace2c4147eea098b867df1ae6e24cfdda991e7d490c95114ee1a473979d171232485c420b38c52f1af547309cf4e66e2c2075d93b056d67c01683b0a0ec

test:
  secret_key_base: 80261f734c3057fb74fbea2bf2f956ff952d04e57cb1f1ae89aaf59260e70a80c41f766204692a043a7d56744d0fd252063564cd3fc1b692e8e74a204e6c068a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
